#!/bin/bash

set -e -u

cd `dirname $0`

### configuration begin
projct_dir="app_android"
ultima_dir="BUILD"
ultima_fil="app.apk"

sh generate_headers
sh program_lua/libluascript/generate_lua
### configutation end

origin_dir="$projct_dir/app/build/outputs/apk/release"
origin_fil="app-release.apk"

# build library
pushd $projct_dir
./gradlew clean
./gradlew assembleRelease
popd

# copy apk
rm    -rf                  $ultima_dir/$ultima_fil
mkdir -p                   $ultima_dir
mv $origin_dir/$origin_fil $origin_dir/$ultima_fil
mv $origin_dir/$ultima_fil $ultima_dir
