#!/bin/bash

set -e -u

cd `dirname $0`

### configuration begin
projct_dir="app_android"
ultima_dir="BUILD"
ultima_fil="as.apk"

sh generate_headers
sh program_game/generate_lua
### configutation end

origin_dir="$projct_dir/app/build/outputs/apk/release"
origin_fil="app-release.apk"

# NOTE:
# file 'local.properties' has a higher priority than the environment variables
export     ANDROID_HOME="$HOME/Library/Android/sdk"
export ANDROID_NDK_HOME="$HOME/Library/Android/sdk/ndk-bundle"

# build library
pushd $projct_dir
./gradlew clean
./gradlew assembleRelease
popd

# copy apk
rm    -rf                  $ultima_dir/$ultima_fil
mkdir -p                   $ultima_dir
mv $origin_dir/$origin_fil $origin_dir/$ultima_fil
mv $origin_dir/$ultima_fil $ultima_dir
