#!/bin/bash

set -e -u

cd `dirname $0`

cur_path=`pwd`

cmd_line="Unity"
cmd_line="$cmd_line -quit"
cmd_line="$cmd_line -batchmode"
cmd_line="$cmd_line -projectPath $cur_path/app_unity"
cmd_line="$cmd_line -executeMethod AndroidBuilder.Build"
cmd_line="$cmd_line -logFile"
$cmd_line

rm   -rf BUILD/unity.apk
mkdir -p BUILD
mv       app_unity/unity.apk BUILD
