#!/bin/bash

set -e -u

cd `dirname $0`

### configuration begin
dst_dir="app_unity/Assets/Plugins"
dst_fil="library"

cpp_dir=""
cpp_dir="$cpp_dir library/BASIS/libbasis"
cpp_dir="$cpp_dir library/ctool/libctool"
cpp_dir="$cpp_dir library/foundation/libfoundation"

obc_dir=""
obc_dir="$obc_dir library/BASIS/ObjcBasis"
obc_dir="$obc_dir library/foundation/IOSFoundation"

sh generate_headers
### configutation end

tmp_dir="TMP"

rm   -rf $tmp_dir
mkdir -p $tmp_dir

# compile *.cpp
for it in `find $cpp_dir -name '*.cpp'`; do
    cmd_line="clang"
    cmd_line="$cmd_line -std=c++14"
    cmd_line="$cmd_line -IGENERATED_HEADERS"
    cmd_line="$cmd_line -c $it"
    cmd_line="$cmd_line -o $tmp_dir/$RANDOM.`basename $it`.o"
    $cmd_line
done

# compile *.m
for it in `find $obc_dir -name '*.m'`; do
    cmd_line="clang"
    cmd_line="$cmd_line -IGENERATED_HEADERS"
    cmd_line="$cmd_line -c $it"
    cmd_line="$cmd_line -o $tmp_dir/$RANDOM.`basename $it`.o"
    $cmd_line
done

# link
mak_arg=""
mak_arg="$mak_arg -dynamiclib"
mak_arg="$mak_arg $tmp_dir/*.o"
mak_arg="$mak_arg -framework Foundation"
mak_arg="$mak_arg -lc++"

rm   -rf $dst_dir/$dst_fil.bundle
mkdir -p $dst_dir/$dst_fil.bundle/Contents/MacOS
clang -o $dst_dir/$dst_fil.bundle/Contents/MacOS/$dst_fil $mak_arg

rm -rf $tmp_dir
