@echo off

pushd %~dp0

set out_dir="..\..\GENERATED_LUA"
set out_fil="..\..\GENERATED_LUA\GENERATED_LUA"

if exist %out_dir% (rmdir /q /s %out_dir%)
mkdir %out_dir%

echo /* the file generated by script, do not modify manually. */ > %out_fil%

for /r %%f in (*.lua) do (
    echo "%%~nxf", >> %out_fil%
    echo R^"===^(  >> %out_fil%
    type %%f       >> %out_fil%
    echo ^)===^",  >> %out_fil%
)

popd
