//==== ==== ==== ==== ==== header ==== ==== ==== ==== ====
static const char *F_HEADER = R"OO(

//[$header]
//this file generated by automation tool, don't modify it manually.

#include "cqbridgeobject.hh"

$loop_cls
cq_declare($cppcls);
$end

$need
$loop_cls
$loop_cls_func
$ret _cpp_$(class)_$func($params);
$end
$end

$loop_cls
cq_class($cppcls, cqBridgeObject) {

$loop_cls_func
    static $ret $func($params);
$end
$loop_obj_func
    virtual $ret $func($params) = 0;
$end
};

$end
)OO";

//==== ==== ==== ==== ==== interface source ==== ==== ==== ==== ====
static const char *intf_source = R"OO(

)OO";

//==== ==== ==== ==== ==== implementation source ==== ==== ==== ==== ====
static const char *impl_source = R"OO(

)OO";
