static const char *F_HEADER = R"OO(

//[$header]
//this file generated by automation tool, don't modify it manually.

#pragma once

#include "cqbridgeobject.hh"

$loop_cls
cq_declare($cppcls);
$end

$need
$loop_cls
$loop_cls_func
$ret _cpp_$(class)_$func($params);
$end
$end

$loop_cls
cq_class($cppcls, cqBridgeObject) {

$loop_cls_func
    static $ret $func($params);
$end
$loop_obj_func
    virtual $ret $func($params) = 0;
$end
};

$end
)OO";

static const char *F_SOURCE = R"OO(

//[$source]
//this file generated by automation tool, don't modify it manually.

#include "$header"

$loop_cls
cq_member($cppcls) {
};

$loop_cls_func
$ret $cppcls::$func($params) {
    $(return)_cpp_$(class)_$func($values);
}

$end
$end
)OO";
