//==== ==== ==== ==== ==== header ==== ==== ==== ==== ====
static const char *intf_header = R"OO(

//$header.
//this file generated by automation tool, don't modify it manually.

#include "CQBridgeObject.h"

$loop_class
@class $objccls;
$end

$need
$loop_class
$loop_static
CQ_C_LINK $(cret)_objc_$(class)_$cfunc($cparams);
$end
$end

$loop_class
@interface $objccls : CQBridgeObject
$loop_static
+ ($memret)$memfunc;
$end
$loop_virtual
- ($memret)$memfunc;
$end
@end

$end
)OO";

//==== ==== ==== ==== ==== interface source ==== ==== ==== ==== ====
static const char *intf_source = R"OO(

)OO";

//==== ==== ==== ==== ==== implementation source ==== ==== ==== ==== ====
static const char *impl_source = R"OO(

)OO";
