//==== ==== ==== ==== ==== header ==== ==== ==== ==== ====
static const char *F_HEADER = R"OO(

//[$header]
//this file generated by automation tool, don't modify it manually.

#include "CQBridgeObject.h"

$loop_cls
@class $objccls;
$end

$need
$loop_cls
$loop_cls_func
CQ_C_LINK $(cret)_objc_$(class)_$cfunc($cparams);
$end
$end

$loop_cls
@interface $objccls : CQBridgeObject
$loop_cls_func
+ ($objcret)$objcfunc;
$end
$loop_obj_func
- ($objcret)$objcfunc;
$end
@end

$end
)OO";

//==== ==== ==== ==== ==== interface source ==== ==== ==== ==== ====
static const char *intf_source = R"OO(

)OO";

//==== ==== ==== ==== ==== implementation source ==== ==== ==== ==== ====
static const char *impl_source = R"OO(

)OO";
