@echo off

pushd %~dp0

set src_dir="usergameup"
set dst_dir="..\GENERATED_LUA"
set dst_fil="..\GENERATED_LUA\GENERATED_LUA"

if exist %dst_dir% (rmdir /q /s %dst_dir%)
mkdir %dst_dir%

echo /* the file generated by script, do not modify manually. */ > %dst_fil%

for /r %src_dir% %%f in (*.lua) do (
    echo "%%~nxf",      >> %dst_fil%
    echo #include "%%f" >> %dst_fil%
    echo ,              >> %dst_fil%
)

popd
